#=
Nurse Rostering MILP — 13-week quarterly roster
==================================================
Ward: 30 nurses (18 RN / 12 SoSu), general medical/surgical
Roster window: one 13-week (91-day) quarter, selected below out of 4
Shifts: Day 07:00-15:00, Evening 15:00-23:00, Night 23:00-07:00(+1), 8h each
Coverage targets: Day 8 (RN>=5), Evening 5 (RN>=3), Night 3 (RN>=2)

This model produces the REGULAR (unbuffered) base roster only — it assumes
full staff availability minus approved vacation. Sick-leave risk is handled
separately by the later simulation/lookahead layer, not here.

Feasibility at TOL=0.15 (below) has been independently verified for all
four quarters using their real generated vacation data (see conversation
history / check_all_quarters.py) — every quarter solves to a feasible
roster, not just in aggregate but day-by-day.

INPUT FILES EXPECTED (adjust DATA_DIR below to match your local folder):
  nurse_profiles.csv              -> shared across all 4 quarters
  vacation_days_scenario{1-4}.csv -> one per quarter, pick via QUARTER below

REQUIRES: JuMP, HiGHS, CSV, DataFrames, Dates, JSON3
  ] add JuMP HiGHS CSV DataFrames JSON3

ASSUMPTIONS FLAGGED INLINE WITH "ASSUMPTION:" — these are modeling judgment
calls, not sourced from the overenskomst, and are the first things to
revisit if the solve looks wrong or you want to tune realism.
=#

import Pkg
Pkg.add("JuMP")
Pkg.add("HiGHS")
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("Dates")
Pkg.add("JSON3")
using JuMP, HiGHS, CSV, DataFrames, Dates, JSON3

# ---------------------------------------------------------------------------
# 0. QUARTER SELECTION — change this to 1, 2, 3, or 4 and re-run
# ---------------------------------------------------------------------------
const QUARTER = 4

const QUARTER_START = Dict(
    1 => Date(2024, 12, 30),
    2 => Date(2025, 3, 31),
    3 => Date(2025, 6, 30),
    4 => Date(2025, 9, 29),
)

# ---------------------------------------------------------------------------
# 1. LOAD DATA
# ---------------------------------------------------------------------------
# ASSUMPTION: adjust this path to wherever your files actually live.
const DATA_DIR = "."

nurses_df   = CSV.read(joinpath(DATA_DIR, "nurse_profiles.csv"), DataFrame)
vacation_df = CSV.read(joinpath(DATA_DIR, "vacation_days_scenario$(QUARTER).csv"), DataFrame)
vacation_df.vacation_date = Date.(vacation_df.vacation_date)

# ---------------------------------------------------------------------------
# 2. SETS
# ---------------------------------------------------------------------------
N = nurses_df.nurse_id                       # nurse IDs, e.g. "N001"
S = [:Day, :Evening, :Night]                 # shift types

const START_DATE = QUARTER_START[QUARTER]
const N_DAYS     = 91                        # 13 weeks
D = 1:N_DAYS                                  # day index, 1 = START_DATE
date_of(d) = START_DATE + Day(d - 1)

# lookup helpers keyed by nurse_id
role            = Dict(r.nurse_id => r.role            for r in eachrow(nurses_df))
contract_pct    = Dict(r.nurse_id => r.contract_pct     for r in eachrow(nurses_df))
night_eligible  = Dict(r.nurse_id => (r.night_eligible == "Yes") for r in eachrow(nurses_df))
contracted_hrs  = Dict(r.nurse_id => r.contracted_weekly_hours for r in eachrow(nurses_df))
hourly_wage     = Dict(r.nurse_id => r.hourly_wage_dkk  for r in eachrow(nurses_df))

# vacation lookup: set of (nurse_id, day_index) pairs
vacation_set = Set{Tuple{String,Int}}()
for r in eachrow(vacation_df)
    d = Dates.value(r.vacation_date - START_DATE) + 1
    if 1 <= d <= N_DAYS
        push!(vacation_set, (r.nurse_id, d))
    end
end

# ---------------------------------------------------------------------------
# 3. SHIFT / COST PARAMETERS
# ---------------------------------------------------------------------------
SHIFT_HOURS = Dict(:Day => 8.0, :Evening => 8.0, :Night => 8.0)

# Per-nurse hourly wage is now loaded directly from nurse_profiles.csv's
# `hourly_wage_dkk` column (see hourly_wage Dict above), generated by
# GenerateNurseScenarios.py from each nurse's role + years_experience,
# not a flat role-only rate. See that script for full sourcing notes:
# RN wage follows real DSR grundløn-by-anciennitet løntrin steps; SoSu
# wage is derived as a fixed ratio of the RN curve (see script comments
# for why a mixed-basis SoSu curve was rejected — it produced an
# unrealistic crossover where SoSu could overtake RN pay at high
# seniority).

# Blended in-shift premium (fraction of the shift's hours that fall in the
# evening/night premium windows, weighted by the OK-24 rates: evening 32%,
# night 37.5%). Derived from the shift-time table we worked out earlier.
WEEKDAY_PREMIUM = Dict(
    :Day     => 0.0,
    :Evening => (5/8) * 0.32,     # 18:00-23:00 falls in the 8h evening shift
    :Night   => (7/8) * 0.375,    # 23:00-06:00 falls in the 8h night shift
)

const WEEKEND_PREMIUM = 0.47   # OK-24 §12 stk.3: Sat 06:00 - Sun 24:00
const HOLIDAY_PREMIUM = 0.50   # OK-24 §12 stk.3: søgnehelligdage

# SOURCED: full set of 2025 Danish public holidays (søgnehelligdage) that
# fall within the four quarters. Confirmed Easter Sunday 2025 = April 20;
# confirmed Store Bededag was permanently abolished from 2024 onward, so
# it's correctly NOT included here. Grundlovsdag (Jun 5) and May 1 are
# NOT official statutory holidays in Denmark, so also correctly excluded.
const HOLIDAYS = Set([
    Date(2025, 1, 1),    # Nytårsdag (New Year's Day) — Q1
    Date(2025, 4, 17),   # Skærtorsdag (Maundy Thursday) — Q2
    Date(2025, 4, 18),   # Langfredag (Good Friday) — Q2
    Date(2025, 4, 20),   # Påskedag (Easter Sunday) — Q2
    Date(2025, 4, 21),   # 2. Påskedag (Easter Monday) — Q2
    Date(2025, 5, 29),   # Kristi Himmelfartsdag (Ascension Day) — Q2
    Date(2025, 6, 8),    # Pinsedag (Whit Sunday) — Q2
    Date(2025, 6, 9),    # 2. Pinsedag (Whit Monday) — Q2
    Date(2025, 12, 25),  # Juledag (Christmas Day) — Q4
    Date(2025, 12, 26),  # 2. Juledag (Boxing Day) — Q4
])

# ASSUMPTION: a shift on Saturday or Sunday is treated as fully "weekend"
# for premium purposes, and holiday overrides weekend which overrides the
# evening/night in-shift premium (no stacking). This simplifies the true
# hour-by-hour split at day/weekend boundaries.
function premium_rate(d::Int, s::Symbol)
    dt = date_of(d)
    if dt in HOLIDAYS
        return HOLIDAY_PREMIUM
    elseif dayofweek(dt) in (6, 7)   # Saturday=6, Sunday=7
        return WEEKEND_PREMIUM
    else
        return WEEKDAY_PREMIUM[s]
    end
end

function shift_cost(n, d::Int, s::Symbol)
    wage = hourly_wage[n]
    hrs  = SHIFT_HOURS[s]
    return wage * hrs * (1 + premium_rate(d, s))
end

# ---------------------------------------------------------------------------
# 4. COVERAGE REQUIREMENTS
# ---------------------------------------------------------------------------
TOTAL_MIN = Dict(:Day => 8, :Evening => 5, :Night => 3)
RN_MIN    = Dict(:Day => 5, :Evening => 3, :Night => 2)

RN_NURSES = [n for n in N if role[n] == "RN"]

# ---------------------------------------------------------------------------
# 5. REST-RULE FORBIDDEN ADJACENCY (11h rule, derived from shift times)
# ---------------------------------------------------------------------------
FORBIDDEN_PAIRS = [(:Evening, :Day), (:Night, :Day), (:Night, :Evening)]

# ---------------------------------------------------------------------------
# 6. WEEKS (for the 48h cap, the ~37h/week average target, and the
#    "at least one day off per week" rule)
# ---------------------------------------------------------------------------
WEEKS = 1:13
days_in_week(w) = ((w - 1) * 7 + 1):(w * 7)

# ---------------------------------------------------------------------------
# 7. MODEL
# ---------------------------------------------------------------------------
model = Model(HiGHS.Optimizer)
set_optimizer_attribute(model, "time_limit", 300.0)   # seconds; raise if needed

@variable(model, x[n in N, d in D, s in S], Bin)

# --- at most one shift per nurse per day ---
@constraint(model, one_shift_per_day[n in N, d in D],
    sum(x[n, d, s] for s in S) <= 1)

# --- coverage: total headcount per shift ---
@constraint(model, coverage_total[d in D, s in S],
    sum(x[n, d, s] for n in N) >= TOTAL_MIN[s])

# --- coverage: RN floor per shift ---
@constraint(model, coverage_rn[d in D, s in S],
    sum(x[n, d, s] for n in RN_NURSES) >= RN_MIN[s])

# --- night eligibility ---
@constraint(model, night_elig[n in N, d in D; !night_eligible[n]],
    x[n, d, :Night] == 0)

# --- vacation hard block ---
@constraint(model, vacation_block[n in N, d in D; (n, d) in vacation_set],
    sum(x[n, d, s] for s in S) == 0)

# --- rest rule: forbidden shift adjacency across consecutive days ---
# (indexed by pair position rather than destructuring the tuple directly,
# to avoid relying on JuMP's container macro supporting tuple unpacking)
@constraint(model, rest_rule[n in N, d in 1:(N_DAYS - 1), p in 1:length(FORBIDDEN_PAIRS)],
    x[n, d, FORBIDDEN_PAIRS[p][1]] + x[n, d + 1, FORBIDDEN_PAIRS[p][2]] <= 1)

# --- at least one full day off per week ---
@constraint(model, day_off_per_week[n in N, w in WEEKS],
    sum(x[n, d, s] for d in days_in_week(w), s in S) <= 6)

# --- weekly hour cap: 48h including any assigned load ---
@constraint(model, weekly_hour_cap[n in N, w in WEEKS],
    sum(x[n, d, s] * SHIFT_HOURS[s] for d in days_in_week(w), s in S) <= 48)

# --- average weekly hours ~= contracted hours over the 13-week quarter
#     (ASSUMPTION: the real overenskomst default normperiode is 14 weeks
#     if no local agreement is reached; this project uses 13-week calendar
#     quarters instead for a cleaner "one per quarter" portfolio framing —
#     worth a one-line disclosure in your writeup, same as any other
#     deliberate deviation from the sourced default.)
#     ASSUMPTION: +/-15% tolerance band around the contracted target.
#     NOTE: at 30 nurses (18 RN/12 SoSu) with the coverage rule of
#     5/3/2 RN-minimum per day, the RN population's contracted hours
#     (~499.5h/week) sit BELOW the 560h/week the RN coverage rule demands.
#     A tolerance band below ~12.1% makes the model provably infeasible
#     (RNs literally cannot supply enough hours even at their individual
#     max) — this minimum-TOL figure is scale-invariant, so it holds at
#     13 weeks exactly as it did at 14. 15% leaves a small safety margin,
#     independently re-verified feasible for all 4 quarters' real vacation
#     data. If you'd rather not lean on that much overtime, the more
#     realistic fix is to add 1-2 more RNs to the ward, or ease the
#     RN-minimum coverage rule slightly.
TOL = 0.15
@constraint(model, avg_hours_lo[n in N],
    sum(x[n, d, s] * SHIFT_HOURS[s] for d in D, s in S) >= contracted_hrs[n] * 13 * (1 - TOL))
@constraint(model, avg_hours_hi[n in N],
    sum(x[n, d, s] * SHIFT_HOURS[s] for d in D, s in S) <= contracted_hrs[n] * 13 * (1 + TOL))

# ---------------------------------------------------------------------------
# 8. FAIRNESS TERM: penalize deviation from an even night-shift split
#    across night-eligible nurses (linearized with deviation variables).
#    ASSUMPTION: fairness only tracked for night shifts here; weekend
#    fairness could be added the same way if you want it later.
# ---------------------------------------------------------------------------
NIGHT_ELIGIBLE_NURSES = [n for n in N if night_eligible[n]]
total_night_slots = TOTAL_MIN[:Night] * N_DAYS
avg_night_target = total_night_slots / length(NIGHT_ELIGIBLE_NURSES)

@variable(model, night_dev[n in NIGHT_ELIGIBLE_NURSES] >= 0)
@constraint(model, night_dev_lo[n in NIGHT_ELIGIBLE_NURSES],
    night_dev[n] >= sum(x[n, d, :Night] for d in D) - avg_night_target)
@constraint(model, night_dev_hi[n in NIGHT_ELIGIBLE_NURSES],
    night_dev[n] >= avg_night_target - sum(x[n, d, :Night] for d in D))

# ---------------------------------------------------------------------------
# 9. OBJECTIVE: minimize total labor cost + fairness penalty
#    ASSUMPTION: FAIRNESS_WEIGHT trades cost against even night distribution
#    in DKK-equivalent units — tune this once you see results.
# ---------------------------------------------------------------------------
const FAIRNESS_WEIGHT = 500.0   # DKK penalty per shift of deviation from target

@objective(model, Min,
    sum(x[n, d, s] * shift_cost(n, d, s) for n in N, d in D, s in S) +
    FAIRNESS_WEIGHT * sum(night_dev[n] for n in NIGHT_ELIGIBLE_NURSES)
)

# ---------------------------------------------------------------------------
# 10. SOLVE
# ---------------------------------------------------------------------------
optimize!(model)

println("Termination status: ", termination_status(model))

if !is_solved_and_feasible(model)
    error("Model did not find a feasible solution (status: $(termination_status(model))). " *
          "No roster to extract — check constraint feasibility (e.g. coverage vs. " *
          "contracted-hours capacity) before proceeding.")
end

println("Objective value (DKK): ", objective_value(model))

# ---------------------------------------------------------------------------
# 11. EXTRACT AND SAVE THE ROSTER
# ---------------------------------------------------------------------------
rows = NamedTuple[]
for n in N, d in D, s in S
    if value(x[n, d, s]) > 0.5
        push!(rows, (
            nurse_id   = n,
            role       = role[n],
            date       = date_of(d),
            day_index  = d,
            shift_type = String(s),
            hours      = SHIFT_HOURS[s],
            premium_pct = premium_rate(d, s) * 100,
            cost_dkk   = shift_cost(n, d, s),
        ))
    end
end

roster_df = DataFrame(rows)
sort!(roster_df, [:date, :shift_type, :nurse_id])

out_path = joinpath(DATA_DIR, "roster_Q$(QUARTER).csv")
CSV.write(out_path, roster_df)
println("Roster written to: ", out_path)
println("Total assigned shifts: ", nrow(roster_df))

# ---------------------------------------------------------------------------
# 12. EXPORT RESULTS JSON — for the website to load in place of mock data.
#     NOTE: coverage compliance is a HARD CONSTRAINT in this model, so it is
#     always 100% whenever the solve succeeds -- this isn't a soft KPI the
#     way the mock version's numbers were. The "Staffing Risk — Lookahead"
#     panel in the site still needs the (not-yet-built) simulation layer;
#     this export only replaces the KPI cards and the weekly-shifts chart.
# ---------------------------------------------------------------------------

weekly_shifts_agg = Dict{Int, Dict{String, Int}}()
for w in WEEKS
    weekly_shifts_agg[w] = Dict("day" => 0, "evening" => 0, "night" => 0)
end
for row in eachrow(roster_df)
    w = ((row.day_index - 1) ÷ 7) + 1
    key = lowercase(row.shift_type)
    weekly_shifts_agg[w][key] += 1
end

weekly_shifts_json = [
    Dict("week" => w,
         "day" => weekly_shifts_agg[w]["day"],
         "evening" => weekly_shifts_agg[w]["evening"],
         "night" => weekly_shifts_agg[w]["night"])
    for w in WEEKS
]

results = Dict(
    "quarter" => QUARTER,
    "kpis" => Dict(
        "totalCost" => objective_value(model),
        "totalShifts" => nrow(roster_df),
        "avgWeeklyHours" => sum(roster_df.hours) / (length(N) * length(WEEKS)),
        "rnCount" => length(RN_NURSES),
        "totalCount" => length(N),
        "nightEligible" => length(NIGHT_ELIGIBLE_NURSES),
        "complianceDay" => 100.0,     # hard constraint -- always met if solved
        "complianceEve" => 100.0,
        "complianceNight" => 100.0,
        "solveTimeSec" => solve_time(model),
        "fairnessDeviation" => sum(value(night_dev[n]) for n in NIGHT_ELIGIBLE_NURSES) / length(NIGHT_ELIGIBLE_NURSES),
    ),
    "weeklyShifts" => weekly_shifts_json,
)

results_path = joinpath(DATA_DIR, "results_Q$(QUARTER).json")
open(results_path, "w") do f
    JSON3.write(f, results)
end
println("Results JSON written to: ", results_path)
